dataset_path: DogNeverSleep/AMBER
dataset_kwargs:
  token: True
task: amber
test_split: train
output_type: generate_until
doc_to_visual: !function utils.amber_doc_to_visual
doc_to_text: !function utils.amber_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.amber_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: amber_score
    aggregation: !function utils.amber_aggregate_results_amber_score
    higher_is_better: true
  - metric: chair
    aggregation: !function utils.amber_aggregate_results_chair
    higher_is_better: false
  - metric: cover
    aggregation: !function utils.amber_aggregate_results_cover
    higher_is_better: true
  - metric: hal
    aggregation: !function utils.amber_aggregate_results_hal
    higher_is_better: false
  - metric: cog
    aggregation: !function utils.amber_aggregate_results_cog
    higher_is_better: false
  - metric: accuracy
    aggregation: !function utils.amber_aggregate_results_accuracy
    higher_is_better: true
  - metric: precision
    aggregation: !function utils.amber_aggregate_results_precision
    higher_is_better: true
  - metric: recall
    aggregation: !function utils.amber_aggregate_results_recall
    higher_is_better: true
  - metric: f1
    aggregation: !function utils.amber_aggregate_results_f1
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0
