dataset_path: kirito011024/vlguard_safe_unsafes
dataset_kwargs:
  token: True
task: "Safe_unsafes"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.multitrust_doc_to_visual
doc_to_text: !function utils.multitrust_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 2048
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.multitrust_vlguard_safe_unsafes_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: ASR
    aggregation: !function utils.multitrust_harmbenchmodel_aggregate_results
    higher_is_better: false
  # - metric: multitrust_crossmodel_rule_reject_template_score
  #   aggregation: !function utils.multitrust_crossmodel_rule_reject_template_aggregate_results
  #   higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Assistant:"
  # gpt4v:
  #   pre_prompt: ""
  #   post_prompt: "Assistant:"
  # qwen_vl:  
  #   pre_prompt: ""
  #   post_prompt: " Assistant:"
metadata:
  - version: 0.0
